sonar.projectKey=2SCloud_scloud-dns
sonar.organization=2scloud

sonar.projectName=scloud-dns
sonar.projectVersion=0.2.3


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1,e2

# kubernetes:S6865 - RBAC managed in 'scloud-eg-compute/platform/rbac' repo
sonar.issue.ignore.multicriteria.e1.ruleKey=kubernetes:S6865
sonar.issue.ignore.multicriteria.e1.resourceKey=**/deployment.yaml

# duplicated code
sonar.issue.ignore.multicriteria.e2.ruleKey=common-java:DuplicatedBlocks
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*